### PR TITLE
Task: T239 homeScreen defaults to selected debitButton

### PR DESCRIPTION
**Pull request by klishevich**
Accomplished subtasks: 
- 5 debitorAccountBalanceDisplayCell with signed in account name in "<account> balance" copy - FAIL: The "Sandy" username is currently hardcoded to display. Since the /account service is available now, change username to value passed by /account.
- 8 a AA battery-shaped button group pair containing a debitbutton and creditButton - Requires adding.

But instead of battery-shaped button, used common button.

### CODE REVIEW

**Comment by mxfactorial** [comment]
Well done. Are you capable of completing the rest of this case and the following one before a merge?

i. Add transactButton (current source icon added later) to bottom of homeScreen when debitButton is selected (default)
ii. Display transactButton as inactive until transaction_item > 0
iii. Replace plus.png inside addGoodOrServiceButton with `(+)` text (no icon in button; text only)
iv. Rename addGoodOrServiceButton to consumeGoodOrServiceButton (if the button is reusable, then declare this value for the button's copy)
v. Display consumeGoodOrServiceButton when debitButton is selected

From there, will be easy to complete "T358 homeScreen after selecting creditButton":
vi. Add requestButton (voltage source icon added later) to bottom of homeScreen when creditButton is selected (may be reusable that passes props to switch copy and object direction)
vii. Display requestButton as inactive until transaction_item > 0 (no extra code necessary if a reusable component)
viii. Display a produceGoodOrServiceButton with the `(-) good or service` text inside when creditButton is selected

**Comment by klishevich** [comment]
Yes. I think so.

**Comment by mxfactorial** [comment]
Continue adding commits. 
Comment 'Ready for code review' when finished.

**Comment by klishevich** [comment]
tests fixed, need to increase coverage

**Comment by klishevich** [comment]
Ready for code review

**Comment by mxfactorial** [comment]
@DGafetdinov please line comment, in kindest terms, questions and/or suggestions. Otherwise, "Ready for testing" if zero critical objections.

**Comment by mxfactorial** [comment]
@klishevich transactButton and requestButton becomes active when transaction_item object > 0 instead of when **completed** transaction_item > 0. To avoid POST of empty object to /transact, require all transaction_item input fields to have values present before displaying active buttons.

**Comment by mxfactorial** [comment]
@klishevich Also, anchor the debitButton, creditButton pair below the sumTransactionItemDisplayCell instead of above the transactButton/requestButton. Prevents pushing the button-pair down as transaction_item(s) are added.

**Comment by klishevich** [comment]
@mxfactorial thanks for comments, all done

**Comment by mxfactorial** [comment]
Passes testing. Code review by @DGafetdinov before merge.

**Comment by mxfactorial** [comment]
@klishevich This pull request has resolved at least 6 cases so far. You're welcome to continue adding for T354 and T356 which are small and relevant changes.

**Comment by klishevich** [comment]
@mxfactorial ok I take T354, T356

**Comment by klishevich** [comment]
@mxfactorial T354 and T356 done

**Pull request merged**
