### PR TITLE
New requests

### PR DESCRIPTION
**Pull request by oozywaters**

### CODE REVIEW

**Comment by oozywaters** [comment]
Ready for review.

**Comment by mxfactorial** [comment]
to avoid e2e inventory test failure, please display `expirationTimeIndicator` with right-aligned, grayed out _none_ value when not set

**Comment by ctophermags** [comment]
Hey Vyacheslav, I've added new tests with current expect statements. Please add code to pass tests.

**Comment by oozywaters** [comment]
Ready for review.

**Pull request merged**
