### PR TITLE
Display toFixed(3) total value amount

### PR DESCRIPTION
**Pull request by oozywaters**

### CODE REVIEW

**Comment by oozywaters** [comment]
#87

**Comment by oozywaters** [comment]
Ready for review

**Comment by mxfactorial** [comment]
`yarn test` fails but [CI didn't execute](https://circleci.com/gh/systemaccounting/mxfactorial/1253#tests/containers/0) because 1. change in react files not detected (see fourth line from bottom: `Directories affected when no previous successful build available: `, and 2. pre-build script wasn't exiting after detecting change in react files.

cannot reproduce first issue locally (changed files in react/ detected):
```bash
$ git log --name-only --oneline master..total-to-fixed | sed -E '/^[a-f0-9]{7}/d' | sed '/^\.circleci$/d' | sort -u
react/e2e/private/homeScreen/homeScreenInventory.test.js
react/e2e/private/homeScreen/transactionAddRemove.test.js
react/src/screens/HomeScreen/components/Transaction/index.js
```

solution to second issue pushed in https://github.com/systemaccounting/mxfactorial/commit/fef0c72f681131d13315926666a13156bd85db17

please merge develop and fix `yarn test`

**Comment by oozywaters** [comment]
Ready for review.

**Pull request merged**
