### PR TITLE
Request detail

### PR DESCRIPTION
**Pull request by nstfkc**

### CODE REVIEW

**Comment by enesTufekci** [comment]
@mxfactorial its ready to merge.

**Comment by nstfkc** [comment]
Its not ready yet.

**Comment by nstfkc** [comment]
Ready to go @mxfactorial

**Comment by mxfactorial** [comment]
Please apply similar:
1. font sizes
2. element sizes
3. margins
4. indents 

screen shot 2018-10-27 at 5 07 15 pm

**Comment by mxfactorial** [comment]
"Time of expire" -> "Time of expiration"

**Comment by mxfactorial** [comment]
Acceptance testing transactionSuccessPopup blocked from "Wrong Password":

screen shot 2018-10-27 at 5 25 21 pm

**Comment by nstfkc** [comment]
> Acceptance testing transactionSuccessPopup blocked from "Wrong Password":

Can you elaborate this. In order to see `successPopUp` you need to enter `TRUE` as password.

Related `e2e test` [here](https://github.com/systemaccounting/mxfactorial/blob/request-detail/react/e2e/private/requestDetailScreen/successModal.test.js)

**Comment by mxfactorial** [comment]
`TRUE` from acceptance test is value returned from `==` comparison with password value. Please test password value instead of setting password value = `TRUE`.

aws-amplify isn't documenting any "test password" method in their [Authentication](https://aws-amplify.github.io/docs/js/authentication) or [authclass](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html) documents. If you don't find, please issue estimation for:

1. npm install [crypto-js](https://www.npmjs.com/package/crypto-js)
2. new `customSignIn()` wrapping `Auth.signIn()`
3. pass user and password to`customSignIn()`
4. `Auth.signIn()` returns signed in user
5. `customSignIn()` adds encrypted password value to custom `credential` property in local storage (only on `Auth.signIn()` success)
6. new `testPassword()` called for all post-`Auth.signIn()` authentication cases (e.g. `if passwordInputField.value == Storage.credential` on request, transact)
7. new `customSignOut()` wrapping `Auth.signOut()`
8. call `customSignOut()` removes custom `credential` property from local storage

Can create encryption key locally for now. Will add custom endpoint later for permanent solution.

**Comment by nstfkc** [comment]
Estimation for new requirement: 2h

**Comment by mxfactorial** [comment]
Approved.

**Comment by nstfkc** [comment]
@mxfactorial its ready to merge

**Comment by mxfactorial** [comment]
@enesTufekci please apply similar:

1. ~~font sizes~~
2. element sizes
3. margins
4. indents

screen_shot_2018-11-10_at_5_58_34_pm-2

**Pull request merged**
