### PR TITLE
Refactor code and make some changes

### PR DESCRIPTION
**Pull request by elvongray**
@mxfactorial  I came across this request on upwork(https://www.upwork.com/jobs/_~01715cb7d8239e7902/). Although the task is yet to be complete, I am submitting this pull request to show what I have done so far as I want the job

### CODE REVIEW

**Comment by mxfactorial** [comment]
These small tasks are intended to increase the project's contributors as well as interaction with the data model for education purposes. If your only intention is payment, complete the proposal & hire steps to obligate the fee you expect.

**Comment by elvongray** [comment]
@mxfactorial I am interested in contributing to the project, I just happen to come across it on upwork. Sorry for the delay in completing the task, I am not feeling to well.

**Comment by mxfactorial** [comment]
Master was updated with https://github.com/systemaccounting/mxfactorial/pull/22. 
[Sync your fork](https://help.github.com/articles/syncing-a-fork/) & resolve conflicts before continuing.

**Comment by elvongray** [comment]
@mxfactorial I think I am through with the cleanup. Please point out any part that is lacking.

**Comment by mxfactorial** [comment]
Excellent work so far.
Kindly remove app/theme/theme.js after confirming the app contains zero references to its contents. The app/theme/ directory will remain for a global variables.scss file.
Keeping the home screen background & fonts, eliminate the difference in theme between the landing & home screens (i.e. unify the template).

**Comment by elvongray** [comment]
Alright

**Comment by mxfactorial** [comment]
If your app/containers/Layout/base.scss is serving the purpose of the intended app/theme/variables.scss, then you've already fulfilled the intent of this requirement and need not create a variables.scss. You may delete the app/theme directory, too.
Notify when 1) the create account screens share the same template as the home screen (excluding the burger menu & nav), and 2) the template code the create account screens were previously referencing is removed. Will test, then merge pending zero defects, and count this task as delivered.

**Comment by elvongray** [comment]
Done @mxfactorial

**Pull request merged**
