### PR TITLE
Tasks T381, T241, T397, T396

### PR DESCRIPTION
**Pull request by klishevich**
Adding the expirationDateInputField to the passwordApproveTransactionPopup, then stripping some properties from the client's POST /transact request which has a dependency on your new debit and credit buttons.
**Initial commit**

### CODE REVIEW

**Comment by klishevich** [comment]
@mxfactorial ready for code review

**Comment by mxfactorial** [comment]
:x: **T381 Fail**

Observed: passwordInputField missing from passwordApproveTransactionPopup.
Expected: passwordInputField displays on passwordApproveTransactionPopup.

:x: **T397 Fail 1**

Observed: POST /transact request sent despite missing passwordInputField on passwordApproveTransactionPopup.
Expected: Selecting okButton on passwordApproveTransactionPopup with missing passwordInputField displays 'Password required' (request requires authentication).

:x: **T397 Fail 2**

Observed: `cr_time` included and `transaction_item.rule_instance_id` excluded.
Expected: `cr_time` excluded and `transaction_item.rule_instance_id` included.

:checkered_flag: **T241 Pass**

:x: **T396 Fail**

Observed: `db_time` included and `transaction_item.rule_instance_id` excluded.
Expected: `db_time` excluded and `transaction_item.rule_instance_id` included.

**Reminder**: [db_time](https://github.com/klishevich/mxfactorial/blob/master/app/selectors/transaction/new-transaction.js#L13) and [cr_time](https://github.com/klishevich/mxfactorial/blob/master/app/selectors/transaction/new-transaction.js#L15) will now be added by POST /transact.

**Comment by klishevich** [comment]
Hi @mxfactorial, I fixed. For now I excluded `db_time` and `cr_time` from TransactionSection.js (https://github.com/klishevich/mxfactorial/blob/pr02/app/components/Transaction/TransactionSection.js#L45 and https://github.com/klishevich/mxfactorial/blob/pr02/app/components/Transaction/TransactionSection.js#L66).
Should I also exclude  `db_time` and `cr_time`  from https://github.com/klishevich/mxfactorial/blob/pr02/transact/crud.js#L41-L43 ?

**Comment by mxfactorial** [comment]
T381 is now a pass. T397 and T396 no longer authenticate POST call. cr_time and db_time still included. rule_instance_id still excluded.

:checkered_flag: **T381 Pass**

:x: **T397 Fail 1**

Observed: POST /transact request sent despite adding **FALSE** password to passwordInputField on passwordApproveTransactionPopup.
Expected: Selecting okButton on passwordApproveTransactionPopup after adding **FALSE** password to passwordInputField displays 'Incorrect password' (request requires passing authentication).

:x: **T397 Fail 2**

Observed: `cr_time` included and `transaction_item.rule_instance_id` excluded.
Expected: `cr_time` excluded and `transaction_item.rule_instance_id` included.

:checkered_flag: **T241 Pass**

:x: **T396 Fail 1**

Observed: `db_time` included and `transaction_item.rule_instance_id` excluded.
Expected: `db_time` excluded and `transaction_item.rule_instance_id` included.

:x: **T396 Fail 2**

Observed: POST /transact request sent despite adding **FALSE** password to passwordInputField on passwordApproveTransactionPopup.
Expected: Selecting okButton on passwordApproveTransactionPopup after adding **FALSE** password to passwordInputField displays 'Incorrect password' (request requires passing authentication).

**Comment by klishevich** [comment]
1) @mxfactorial as I have read In Google.Docs description, rule_instance_id should be empty, for new items

> (NEW) Important Note 2: All transaction_item objects possess a rule_instance_id property identifying the rule causing their creation. If the transaction_item is extemporaneous (user-generated at the time of transaction), the rule_instance_id property is empty.

If it is not true I need to know with what value initialize rule_instance_id?

2) db_time and cr_time are added by POST /transact, as they should be, I deleted them from `TransactionSection.js` in my last commit? If I am wrong I need clear instructions.

**Comment by mxfactorial** [comment]
1) The `rule_instance_id` property was missing; not empty. If item is created at transact time (not rule generated), then `rule_instance_id` is initialized as empty.

2) So long as db_time and cr_ time are server generated after user passes authentication (not transmitted by client) they're not fails.

**Comment by klishevich** [comment]
1) I see `rule_instance_id` in my firebase and do you?
screen shot 2016-09-12 at 07 54 10

**Comment by mxfactorial** [comment]
@klishevich New test produces your result: `rule_instance_id` is present in each transaction_item. 

With `cr_time` and `db_time` added by /transact, the only fail is auth on POST /transact. Since auth on POST is essential to adding the next endpoint, will you add this feature? Nothing fancy, same as homeScreen:

false-password

Display 'Incorrect password' below passwordInputField on passwordApproveTransactionPopup IF /transact rejects request **because** password is false.

:checkered_flag: **T381 Pass**

:x: **T397 Fail**

Observed: POST /transact request sent despite adding **FALSE** password to passwordInputField on passwordApproveTransactionPopup.
Expected: Selecting okButton on passwordApproveTransactionPopup after adding **FALSE** password to passwordInputField displays 'Incorrect password' (request requires passing authentication).

:checkered_flag: **T241 Pass**

:x: **T396 Fail**

Observed: POST /transact request sent despite adding **FALSE** password to passwordInputField on passwordApproveTransactionPopup.
Expected: Selecting okButton on passwordApproveTransactionPopup after adding **FALSE** password to passwordInputField displays 'Incorrect password' (request requires passing authentication).

**Comment by klishevich** [comment]
OK, I will add auth on POST /transact

**Comment by klishevich** [comment]
@mxfactorial all done, ready for code review

**Comment by mxfactorial** [comment]
@hotay Will code review tomorrow.

**Comment by mxfactorial** [comment]
@klishevich , @hotay requires another day.

**Review by hotay — COMMENTED** [review]
Look good to me

**Pull request merged**
