### PR TITLE
Feature/post transact form

### PR DESCRIPTION
**Pull request by hotay**
https://github.com/systemaccounting/mxfactorial/issues/38
https://github.com/systemaccounting/mxfactorial/issues/37
https://github.com/systemaccounting/mxfactorial/issues/36

### CODE REVIEW

**Comment by hotay** [comment]
@mxfactorial resolve 3 issues and bump up test coverage to 100%. Please help to check.

**Comment by mxfactorial** [comment]
Thank you for all this excellent work.

Bug 1: [Proptype failure](https://drive.google.com/file/d/0B9xlXsaN9dVQX0VCOGJPLUJxV3M/view?usp=sharing) occurs before posting to create account service (registration).

Bug 2: cr_account & name property values [missing from transactionItem object](https://drive.google.com/file/d/0B9xlXsaN9dVQRUFiZWpDTXhUS28/view?usp=sharing) (property value for cr_author in transaction object exists, though)

**Comment by hotay** [comment]
@mxfactorial Those issues had been fixed

**Comment by mxfactorial** [comment]
Bug 1 & Bug 2 fixed.

Bug 3: Selecting the okButton after leaving passwordInputField empty displays a "Password required" indicator inside the passwordInputField - Fails, transaction submitted as though a password is present in the input field.

**Pull request merged**
