### PR TITLE
DevDep

### PR DESCRIPTION
**Pull request by ghost**
Missing dependency

### CODE REVIEW

**Comment by mxfactorial** [comment]
Share the error produced from this missing dependency.

**Comment by ghost** [comment]
Error: 'nodemon' is not recognized as an internal or external command, operable program or batch file.

**Comment by mxfactorial** [comment]
And the process or command producing this error.?

**Comment by ghost** [comment]
Command in Command Prompt: 'npm run monitor' produces error: "'nodemon' is not recognized as an internal or external command, operable program or batch file."

**Comment by mxfactorial** [comment]
The use case you're identifying is serviced by following step 9 in the most recent version of the https://github.com/systemaccounting/mxfactorial/wiki/Code-Delivery-Workflow where webpack-dev-server offers an automatic refresh feature during development.

However, if you prefer to use nodemon, add it to your local environment without installing it as a dev dependency in the project: i) `npm install nodemon`, then ii) `nodemon main.js` (skipping npm script invocation).

**Pull request closed without merging**
