### PR TITLE
testcase-259

### PR DESCRIPTION
**Pull request by codebru0724**
New email address displays in emailAddressInputField.

### CODE REVIEW

**Comment by mxfactorial** [comment]
@klishevich your first code review awaits. As kindly as possible, line comment any objections. If zero critical objections, comment "Ready for testing".

**Comment by klishevich** [comment]
Good job! 
There is a test coverage decrease, and it would be good to write test to check changed email is displayed, if you know how to write such a test. I do not know :), so I have no critical objections for the PR. 
Ready for testing.

**Comment by mxfactorial** [comment]
@PaulJosten Is it within your means to return code coverage to 100%?

**Comment by mxfactorial** [comment]
@hotay Will you recommend a test for this PR to return coverage to 100%?

**Pull request merged**
