### PR TITLE
Storing credit and debit requests

### PR DESCRIPTION
**Pull request by oozywaters**

### CODE REVIEW

**Comment by oozywaters** [comment]
Ready for review.

**Comment by mxfactorial** [comment]
**steps**
1. sign in as Person1
1. select creditButton to increase balance from transaction
1. add Person2 to recipientInput
1. add bread,2.00,2
1. select requestButton

**observed**
```
mysql> (SELECT id, name, debitor, creditor, debitor_approval_time, creditor_approval_time FROM transactions ORDER BY id DESC LIMIT 2) ORDER BY id\G
*************************** 1. row ***************************
                    id: 436
                  name: bread
               debitor: Person1
              creditor: Person2
 debitor_approval_time: 2019-04-27 16:49:54
creditor_approval_time: NULL
*************************** 2. row ***************************
                    id: 437
                  name: 9% state sales tax
               debitor: Person1
              creditor: StateOfCalifornia
 debitor_approval_time: 2019-04-27 16:49:54
creditor_approval_time: NULL
2 rows in set (0.01 sec)
```

**expected**
```
mysql> (SELECT id, name, debitor, creditor, debitor_approval_time, creditor_approval_time FROM transactions ORDER BY id DESC LIMIT 2) ORDER BY id\G
*************************** 1. row ***************************
                    id: 436
                  name: bread
               debitor: Person2
              creditor: Person1
 debitor_approval_time: NULL
creditor_approval_time: 2019-04-27 16:49:54
*************************** 2. row ***************************
                    id: 437
                  name: 9% state sales tax
               debitor: Person2
              creditor: StateOfCalifornia
 debitor_approval_time: NULL
creditor_approval_time: 2019-04-27 16:49:54
2 rows in set (0.01 sec)
```

**EXCEPTION**: fix rule-generated item later

**Comment by oozywaters** [comment]
Add e2e test case on transaction request: request timeout < 5s after && status===200
**Estimate: +1h**

**Comment by mxfactorial** [comment]
+1h approved

**Comment by oozywaters** [comment]
Ready for review.

**Pull request merged**
