### PR TITLE
Add mock GraphQL rules query endpoint

### PR DESCRIPTION
**Pull request by oozywaters**

### CODE REVIEW

**Comment by oozywaters** [comment]
Ready for review.

**Comment by mxfactorial** [comment]
**expected**
10. if (rule_instance_id), new sales tax object displays **below** all user-generated transaction items in client

**observed**

screen_shot_2019-01-05_at_12_58_01_pm

**REQUIREMENT CHANGE**
please add incremental estimation for passing `ALL rule-generated items displays BELOW requestButton/transactButton` e2e test

screen_shot_2019-01-05_at_1_21_55_pm

**Comment by mxfactorial** [comment]
**observed**
mixing of user and rule generated items:
screen shot 2019-01-05 at 1 03 13 pm

please add incremental estimation for passing tests:
1. `rule-generated item sequence contains 0 user-generated items`
2. `user-generated item sequence contains 0 rule-generated items`

**Comment by mxfactorial** [comment]
**expected**
8. with client assuming 1 quantity default, 1 additional transaction object returned from /rules containing "9% state sales tax" and price = 1 quantity x 1.09 x 5.00 milk price

**observed**
0 quantity default for user-generated item (empty quantity input != 1)



please add e2e coverage

**Comment by mxfactorial** [comment]
[toEqual](https://github.com/systemaccounting/mxfactorial/blob/rules-query/react/e2e/private/homeScreen/transactionAddRemove.test.js#L24) only, please.

**Comment by oozywaters** [comment]
Additional estimate: 2h

**Comment by oozywaters** [comment]
> [toEqual](https://github.com/systemaccounting/mxfactorial/blob/rules-query/react/e2e/private/homeScreen/transactionAddRemove.test.js#L24) only, please.

Are you sure? There may be rule-generated objects which increase total amount value.

**Comment by mxfactorial** [comment]
Yes, these tests receive rules and user-added objects as controlled inputs. Issues with predicting which object will appear or disappear will be remedied by nesting input group in component with clear button as root, then adding integers as data-ids to new element for predicting changes. TODO: Input group component refactoring.

2h incremental estimation approved.

**Comment by oozywaters** [comment]
Ready for review.

**Pull request merged**
