### PR TITLE
Feature/account setting page

### PR DESCRIPTION
**Pull request by hotay**

### CODE REVIEW

**Comment by hotay** [comment]
@mxfactorial this PR is ready to test

You must login with correct username and password to update profile. Login feature just partly complete.

**Comment by mxfactorial** [comment]
UI for change email & password is delivered. However, testing of change password feature is delayed until after the auth feature is complete. Testing of change email address feature is delayed until after the email notification feature is complete. Please accept potential bug reports related to change password as part of the deliverable for auth.

**Bug 1**: Selecting the saveButton on the editProfileScreen updates the database's initial account_profile object.

**Expected result for Bug 1**: In the same way transaction_item is a nested array in transactions, account_profile must be a nested array in accounts. Therefore, after selecting the saveButton on the editProfileScreen, the new account_profile object received by the endpoint is _added to the array_ rather than used to replace an existing account_profile object. Persisting historical versions of the account_profile object in an array is required to service a transaction record dependency. Also, confirm the created_time property is server-generated; not included in the client post.

**Agile request 1**: Add backButton to editProfileScreen.
**Agile request 2**: Link new backButton on editProfileScreen to previous screen recorded by router (accountSettingsScreen).
**Agile request 3**: Change the "accounts" & transactions" collection names in the realtime database to "account" & "transaction", i.e. remove plural 's'.
**Agile request 4**: Clear account creation form values from state IF response from /account POST = 200

**Comment by hotay** [comment]
@mxfactorial this PR is ready for test

**Comment by mxfactorial** [comment]
Testing.

**Pull request merged**
