### PR TITLE
Refactor request detail screen styles

### PR DESCRIPTION
**Pull request by oozywaters**

### CODE REVIEW

**Comment by oozywaters** [comment]
Ready for review

**Comment by mxfactorial** [comment]
Also, please:
1. add space between [negative sign and transaction amount](https://github.com/systemaccounting/mxfactorial/blob/ce5a02110479cd49bd68ab5092ea7231c5a55092/react/src/screens/RequestDetailScreen/RequestDetailScreen.js#L61)
2. set same coloring, indentation and sizes as wireframe:

screen shot 2018-11-14 at 9 35 44 pm

**Comment by oozywaters** [comment]
Ready for review

**Comment by mxfactorial** [comment]
@enesTufekci [custom testPassword()](https://github.com/systemaccounting/mxfactorial/pull/70#issuecomment-433724524) broken:

screen shot 2018-11-15 at 6 50 36 pm

Vyacheslav, **please comment estimation** for fixing new `testPassword()` implementation began by Enes:
1. Sign In
2. Add encrypted password value to storage
3. Navigate to requestDetailScreen
4. Select transactButton to display passwordApproveTransactionPopUp
5. Add password to passwordInputField
6. select okButton to call new `testPassword()`

**expected**
transactionSuccessPopup displays

**note**
custom `testPassword()` implementation added because cognito in [aws-amplify](https://github.com/systemaccounting/mxfactorial/blob/2a22c02e6253e0a5e09477889a69ad188126ba11/react/package.json#L7) does not ship with function to authenticate actions besides sign in. since request approval requires password authentication, must implement `testPassword()`.

Also, please return icons to color from `develop ` branch:

screen shot 2018-11-15 at 6 58 14 pm

**Comment by mxfactorial** [comment]
`testPassword()` commit: [2dbd4e1](https://github.com/systemaccounting/mxfactorial/commit/2dbd4e1f4e452b9315c2cf39a6809825e182fbf9)

**Comment by mxfactorial** [comment]
@enesTufekci after clearing cache:

screen shot 2018-11-17 at 12 40 39 pm

Vyacheslav, 1 hour added to estimation to fix e2e on ci.

**Pull request merged**
